blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.post_list, name='list'),
    path('create/', views.post_create, name='post_create'),
    path('(<id>\d+)/<slug>[\w-]+/', views.post_detail, name='post_detail'),
    path('<slug>[\w-]+/edit/', views.post_update, name='update'),
    path('<slug>[\w-]+/delete/', views.post_delete, name='post_delete'),

]

clothing/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('social-auth/',include('social_django.urls', namespace='social')),
    path('productcreate/',include('productCreate.urls', namespace='productcreate')),
    path('blog/',include('blog.urls', namespace='blog')),
    path('marketing/',include('marketing.urls', namespace='marketing')),
    path('',include('home.urls', namespace='home')),
    path('order/',include('order.urls', namespace='order')),
    path('owner/',include('owner.urls', namespace='owner')),
    path('product_search/',include('search.urls', namespace='product_search')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('tracking/', include('tracking.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    # path("paystack", include(('paystack.urls', 'paystack'), namespace='paystack')),
]
if settings.DEBUG:urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_list, name='home'),
    path('category_chart/', views.category_chart, name='category_chart'),
    path('ads_list', views.ads_list, name='ads_list'),
    path('allads_list', views.allads_list, name='allads_list'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('favourites/', views.ads_favourite_list, name="favourites"),
    path('favourite_ads/', views.favourite_ads, name="favourite_ads"),
    path('<slug:category_slug>/', views.ads_list, name='ads_list_by_category'),
    path('delete_post/(<pk>\d+)/', views.delete_post, name='delete_post'),
    path('<int:id>/favourite_ad/',views.favourite_ad, name='favourite_ad'),
    path('<int:id>/favourite_delete/',views.favourite_delete, name='favourite_delete'),
    path('<int:id>/<slug:slug>/', views.ad_detail, name='ad_detail'),
    path('category_count/',views.category_count,name='category_count'),
    path('ajax/load-subs/', views.load_subcategories, name='ajax_load_subs'),

]

productCreate/urls.py
from django.urls import path
from . import views

app_name = 'productCreate'

urlpatterns = [
    path('edit_post/(<pk>\d+)/', views.editAd, name='edit_post'),
    path('post/', views.postAd, name='post'),
    path('ajax/load-subcategories/', views.load_subcategories, name='ajax_load_subcategories'),  # <-- this one here
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from productCreate.models import Products, ProductsImages, Category, SubCategory,ProductSize
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.db.models import Q
from django.contrib import messages
from django.http import HttpResponseRedirect, Http404,HttpResponse, JsonResponse
from django.contrib.auth.models import User
from django.urls import reverse
import json
from django.core import serializers
import ast
# Create your views here.
from django.views.decorators.csrf import csrf_exempt
from account.models import Profile
from django.core.mail import send_mail
from hitcount.views import HitCountDetailView
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
# from tracking.models import Visitor
from datetime import datetime
from blog.models import Post
from cart.forms import CartAddProductForm
from django.views.decorators.http import require_POST
from order.models import OrderItem, Order
from star_ratings.models import Rating
from star_ratings.models import UserRating


@login_required
def dashboard(request, category_slug=None):
    category = None
    ads = Products.objects.all()
    latests = Products.objects.filter(available=True).order_by('-created', '?')[:6]
    categories = Category.objects.all()
    users = User.objects.all()
    # visitor = Visitor.objects.filter(start_time=datetime.today())
    blog = Post.objects.all()
    order = Order.objects.all()
    counts = Products.objects.all().values('category__name').annotate(total=Count('category'))

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        ads = ads.filter(category=category)
    return render(request,'home/dashboard.html', {'category': category,'categories': categories,'ads': ads,'latests':latests,
                                              'users':users,'blog':blog,'order':order})


def category_chart(request):
    labels = []
    data = []

    queryset = Products.objects.values('category__name').annotate(category_total=Count('category'))
    print(queryset)
    for entry in queryset:
        labels.append(entry['category__name'])
        data.append(entry['category_total'])

    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })



def home_list(request, category_slug=None):
    category = None
    ads = Products.objects.filter(available=True).order_by("?")[:6]
    queryset_list = Post.objects.filter(draft=False).order_by('-timestamp', '?')[:3]
    latests = Products.objects.filter(available=True).order_by('-created', '?')[:6]
    qs = Products.objects.all()
    categories = Category.objects.all()
    subcategories = SubCategory.objects.all()

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        ads = ads.filter(category=category)
    return render(request,'home/index.html', {'category': category,'categories': categories,'ads': ads,'latests':latests,
                                              'queryset': qs,'subcategories':subcategories,'queryset_list':queryset_list})

def ads_list(request, category_slug=None):
    category = None
    ad_list = Products.objects.filter(available=True)
    order = request.GET.get('order', '-created_date')
    ad_list = ad_list.order_by(order)
    latests = Products.objects.filter(available=True).order_by('-created', '?')[:6]
    qs = Products.objects.all()
    categories = Category.objects.all()
    subcategories = SubCategory.objects.all()
    sizes = ProductSize.objects.all()


    is_favourite = False

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        ad_list = ad_list.filter(category=category)

    paginator = Paginator(ad_list, 2)
    page_request_var = "page"
    page = request.GET.get('page')
    try:
        ads = paginator.page(page)
    except PageNotAnInteger:
        ads = paginator.page(1)
    except EmptyPage:
        ads = paginator.page(paginator.num_pages)
    return render(request,'home/product_list.html', {'category': category,'categories': categories,'ads': ads,'latests':latests,
                                              'queryset': qs,'is_favourite': is_favourite,'order': order,'page': page,
                                              'subcategories':subcategories,'sizes':sizes})



# admin ad list
@login_required
def allads_list(request, category_slug=None):
    category = None
    ad_list = Products.objects.all().order_by('-created', '?')
    categories = Category.objects.all()
    states = Products.objects.all()
    sizes = ProductSize.objects.all()
    query = request.GET.get('q')
    if query:
        ad_list = ad_list.filter(
            Q(first_name__icontains=query) |
            Q(last_name__icontains=query) |
            Q(phone=query) |
            Q(description__icontains=query) |
            Q(address__icontains=query)
        )

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        ad_list = ad_list.filter(category=category)

    paginator = Paginator(ad_list, 10)
    page_request_var = "page"
    page = request.GET.get('page')
    try:
        ads = paginator.page(page)
    except PageNotAnInteger:
        ads = paginator.page(1)
    except EmptyPage:
        ads = paginator.page(paginator.num_pages)
    return render(request,'home/allads_list.html', {'category': category,'categories': categories,'ads': ads,
                                              'states':states,'sizes':sizes})


def ad_detail(request, id, slug):
    ad = get_object_or_404(Products,
                                id=id,
                                slug=slug,
                                available=True)
    adsimage = ProductsImages.objects.filter(products=ad)
    ad_similar = Products.objects.filter(category=ad.category).exclude(id=ad.id).order_by('?')[:7]
    latests = Products.objects.filter(available=True).order_by('-created', '?')[:6]
    profile = Profile.objects.get(user=ad.profile.user)
    categories = Category.objects.all()
    try:
        rating = Rating.objects.get(object_id=ad.id)
    except Rating.DoesNotExist:
        rating = None
    user_rating = UserRating.objects.filter(rating__object_id=ad.id)
    is_favourite = False

    if ad.favourite.filter(id=request.user.id).exists():
        is_favourite = True
    cart_product_form = CartAddProductForm()
    return render(request, 'home/detail.html', {'ad':ad,'adsimage':adsimage, 'ad_similar':ad_similar,
                                               'profile':profile,'latests':latests,'is_favourite': is_favourite,
                                                'categories': categories,'cart_product_form': cart_product_form,
                                                'rating':rating, 'user_rating':user_rating})
@login_required
def ads_favourite_list(request):
    user = request.user
    favourite_posts = user.favourite.all()
    context = {
        'favourite_posts': favourite_posts,
    }
    return render(request, 'owner/bookmarked.html', context)

@login_required
def favourite_ad(request, id):
    ad = get_object_or_404(Products, id=id)
    print(ad)
    if ad.favourite.filter(id=request.user.id).exists():
        ad.favourite.remove(request.user)
    else:
        ad.favourite.add(request.user)

    return HttpResponseRedirect(ad.get_absolute_url())

@login_required
def favourite_delete(request, id):
    ad = get_object_or_404(Products, id=id)
    print(ad)
    if ad.favourite.filter(id=request.user.id).exists():
        ad.favourite.remove(request.user)
    else:
        ad.favourite.add(request.user)

    return redirect('home:favourites')


@login_required
@require_POST
def favourite_ads(request):
    ad = get_object_or_404(Products, id=request.POST.get('id'))
    is_favourite = False
    if ad.favourite.filter(id=request.user.id).exists():
        ad.favourite.remove(request.user)
        is_favourite = False
    else:
        ad.favourite.add(request.user)
        is_favourite = True
    context = {
        'ad': ad,
        'is_favourite': is_favourite,
    }
    if request.is_ajax():
        html = render_to_string('home/special_section.html',context, request=request)
        return JsonResponse({'form': html})


@login_required
def delete_post(request,pk=None):
    ad = Products.objects.get(id=pk)
    if request.user != ad.profile.user:
        raise Http404()
    ad.delete()
    messages.success(request, "You property has been successfuly deleted")
    return redirect('home:allads_list')

@login_required
def customer_list(request):
    customers_list = Profile.objects.all()
    query = request.GET.get('q')
    if query:
        customers_list = customers_list.filter(
            Q(first_name__icontains=query) |
            Q(last_name__icontains=query) |
            Q(phone=query) |
            Q(description__icontains=query) |
            Q(address__icontains=query)
        )
    paginator = Paginator(customers_list, 6)
    page_request_var = "page"
    page = request.GET.get('page')
    try:
        customers = paginator.page(page)
    except PageNotAnInteger:
        customers = paginator.page(1)
    except EmptyPage:
        customers = paginator.page(paginator.num_pages)
    return render(request, 'home/customer_list.html', {'customers':customers})

def category_count(request):
    counts = Products.objects.all().values('category__name').annotate(total=Count('category'))
    lates = Products.objects.order_by('-created_date')[:3]
    return render(request, 'home/footer.html', {'counts': counts, 'lates':lates})

def load_subcategories(request):
    cat_id = request.GET.get('category')
    subcategories = SubCategory.objects.filter(category_id=cat_id).order_by('name')

templates/home/allads_list.html
{% extends "base_admin.html" %}
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
{% load thumbnail %}
{% load humanize %}
{% load hitcount_tags %}

{% block title %}Property List{% endblock %}

{% block content %}
  <div class="container-fluid">
  <!-- ============================================================== -->
  <!-- Bread crumb and right sidebar toggle -->
  <!-- ============================================================== -->
  <div class="row page-titles">
    <div class="col-md-6 align-self-center">
      <h3>Product List</h3>
    </div>
    <div class="col-md-6 text-right font-12"> <a href="index.html">Admin</a>  &gt; Product List</div>
    <div class="">
      <button class="right-side-toggle waves-effect waves-light bg-primary btn btn-circle btn-sm pull-right ml-10"><i class="ti-settings text-white"></i></button>
    </div>
  </div>
  <!-- ============================================================== -->
  <!-- Start Page Content -->
  <!-- ============================================================== -->
  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-12">
          <div class="table-responsive">
            <table id="myTable" class="table color-table table-bordered product-table table-hover">
                <thead>
                  <tr>
                     <td>ID</td>
                     <td>Product</td>
                     <td>Category</td>
                     <td>Price</td>
                     <td>QTY</td>
                     <td>Status</td>
                     <td class="op-0">&nbsp;</td>
                    <td class="op-0">&nbsp;</td>
                  </tr>
                </thead>
                <tbody>
                {% for ad in ads %}
                  <tr>
                     <td>{{ ad.id }}</td>
                     <td class="text-dark weight-600">
                      {% for images in ad.get_second_image %}
                        {% thumbnail images.product_image "50x50" crop="10px 10px"  as im %}
                            <img  style="margin:{{ im|margin:"50x50" }}" src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}">
                            <a href="{{ ad.get_absolute_url }}">{{ ad.title }}</a> <br>
                        {% endthumbnail %}
                      {% endfor %}
                     </td>
                     <td>{{ ad.category }}</td>
                     <td>₦{{ ad.price|intcomma}}</td>
                     <td>25</td>
                     <td>{{ ad.get_status_display }}</td>
                     <td class="text-center"><a href="{% url 'productcreate:edit_post' pk=ad.pk %}"><i class="fa fa-pencil"></i></a></td>
                         <td class="text-center"><a href="{% url 'owner:delete_post' pk=ad.pk %}"><i class="fa fa-trash text-danger"></i></a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

templates/home/customer_list.html
{% extends "base_admin.html" %}
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
{% load thumbnail %}
{% load humanize %}
{% load hitcount_tags %}

{% block title %}Customer List{% endblock %}

{% block content %}
  <div class="container-fluid">
  <!-- ============================================================== -->
  <!-- Bread crumb and right sidebar toggle -->
  <!-- ============================================================== -->
  <div class="row page-titles">
    <div class="col-md-6 align-self-center">
      <h3>Customer List</h3>
    </div>
    <div class="col-md-6 text-right font-12"> <a href="index.html">Admin</a>  &gt; Customer List</div>
    <div class="">
      <button class="right-side-toggle waves-effect waves-light bg-primary btn btn-circle btn-sm pull-right ml-10"><i class="ti-settings text-white"></i></button>
    </div>
  </div>
  <!-- ============================================================== -->
  <!-- Start Page Content -->
  <!-- ============================================================== -->
  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-12">
          <div class="table-responsive">
            <table id="myTable" class="table color-table table-bordered product-table table-hover">
                <thead>
                  <tr>
                     <th>User</th>
                     <th>Opened By</th>
                     <th>Email</th>
                     <th>Phone</th>
                     <th>Address</th>
                     <th>Date Created</th>
{#                     <th>Action</th>#}
                  </tr>
                </thead>
                <tbody>
                {% for customer in customers %}
                  <tr>
                     <td><img src="{{ customer.photo.url }}" alt="" title="" class="profile-img2 img-circle"></td>
                     <td>{{ customer.user.get_full_name }}</td>
                     <td>{{ customer.user.email }}</td>
                     <td>{{ customer.phone }}</td>
                     <td>{{ customer.address }}</td>
                     <td>{{ customer.created }}</td>
{#                     <td><a href="#" class="pencil-icon"><i class="fa fa-pencil" aria-hidden="true"></i></a> <a href="#" class="delete-icon"><i class="fa fa-trash" aria-hidden="true"></i></a></td>#}
                  </tr>
                {% endfor %}
                </tbody>
              </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

templates/home/favourite_section.html
{% if request.user.is_authenticated %}

    {% if request.user in ad.favourite.all %}
        {% csrf_token %}
         <a href="#" id="favourite" data-id="{{ ad.id }}" >
            <i class="lni-heart-filled"></i>
        </a>

    {% else %}
         <a href="#" id="favourite" data-id="{{ ad.id }}" >
            <i class="ti-heart"></i>
        </a>
    {% endif %}
{% else %}
    <a href="{% url 'home:favourite_ad' id=ad.id %}" >
        <i class="ti-heart"></i>
    </a>
{% endif %}

templates/home/index.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
{% load thumbnail %}
{% load humanize %}
{% load hitcount_tags %}

{% block title %}{% endblock %}

{% block content %}

<!-- START SECTION BANNER -->
<div class="banner_section slide_medium shop_banner_slider staggered-animation-wrap">
    <div id="carouselExampleControls">
        <div class="carousel-inner">
            <div class="carousel-item active background_bg" data-img-src="{% static 'assets/images/banner3.jpg' %}">
                <div class="banner_slide_content">
                    <div class="container"><!-- STRART CONTAINER -->
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="banner_content overflow-hidden">
                                	<h5 class="mb-3 staggered-animation font-weight-light" data-animation="slideInLeft" data-animation-delay="0.5s">Taking your Viewing Experience to Next Level</h5>
                                    <h2 class="staggered-animation" data-animation="slideInLeft" data-animation-delay="1s">Summer Sale</h2>
                                    <a class="btn btn-fill-out rounded-0 staggered-animation text-uppercase" href="shop-left-sidebar.html" data-animation="slideInLeft" data-animation-delay="1.5s">Shop Now</a>
                                </div>
                            </div>
                        </div>
                    </div><!-- END CONTAINER-->
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev"><i class="ion-chevron-left"></i></a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next"><i class="ion-chevron-right"></i></a>
    </div>
</div>
<!-- END SECTION BANNER -->

<!-- END MAIN CONTENT -->
<div class="main_content">


<!-- START SECTION SHOP -->
<div class="section small_pt pb_70">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-6">
            	<div class="heading_s1 text-center">
                	<h2>Exclusive Products</h2>
                </div>
            </div>
		</div>
        <div class="row">
        	<div class="col-12">
                <div class="tab-content">
                	<div class="tab-pane fade show active" id="arrival" role="tabpanel" aria-labelledby="arrival-tab">
                        <div class="row shop_container">
                            {% for ad in ads %}
                                <div class="col-lg-3 col-md-4 col-6">
                                    <div class="product">
                                        <span class="{{ ad.get_label_display }}">{{ ad.status }}</span>
                                        <div class="product_img">
                                            <a href="{{ ad.get_absolute_url }}">
                                                {% for images in ad.get_second_image %}
                                                    {% thumbnail images.product_image "330x283" crop="10px 10px"  as im %}
                                                            <img  style="margin:{{ im|margin:"330x283" }}" src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}"  />
                                                    {% endthumbnail %}
                                                {% endfor %}
                                            </a>
                                            <div class="product_action_box" id = "part{{ ad.id }}">
                                                {% include 'home/special_section.html' %}
                                            </div>
                                        </div>
                                        <div class="product_info">
                                            <h6 class="product_title"><a href="{{ ad.get_absolute_url }}">{{ ad.title }}</a></h6>
                                            <div class="product_price">
                                                {% if ad.discount_price %}
                                                    <span class="price">₦{{ ad.discount_price|intcomma}}</span>
                                                    <del>₦{{ ad.price|intcomma}}</del>
                                                 {% else %}
                                                    <span class="price">₦{{ ad.price|intcomma}}</span>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END SECTION SHOP -->

<!-- START SECTION SINGLE BANNER -->
<div class="section bg_light_blue2 pb-0 pt-md-0">
	<div class="container">
    	<div class="row align-items-center flex-row-reverse">
            <div class="col-md-6 offset-md-1">
            	<div class="medium_divider d-none d-md-block clearfix"></div>
            	<div class="trand_banner_text text-center text-md-left">
                    <div class="heading_s1 mb-3">
                        <span class="sub_heading">New season trends!</span>
                        <h2>Best Summer Collection</h2>
                    </div>
                    <h5 class="mb-4">Sale Get up to 50% Off</h5>
                    <a href="{% url 'home:ads_list' %}" class="btn btn-fill-out rounded-0">Shop Now</a>
                </div>
            	<div class="medium_divider clearfix"></div>
            </div>
            <div class="col-md-5">
                <div class="text-center trading_img">
                    <img src="{% static 'assets/images/tranding_img.png' %}" alt="tranding_img"/>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END SECTION SINGLE BANNER -->

<!-- START SECTION SHOP -->
<div class="section">
	<div class="container">
    	<div class="row justify-content-center">
			<div class="col-md-6">
            	<div class="heading_s1 text-center">
                	<h2>Featured Products</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
            	<div class="product_slider carousel_slider owl-carousel owl-theme nav_style1"  data-dots="false" data-nav="true" data-margin="20" data-responsive='{"0":{"items": "1"}, "481":{"items": "2"}, "768":{"items": "3"}, "1199":{"items": "4"}}'>
                	{% for latest in latests %}
                    <div class="item">
                        <div class="product">
                            <span class="{{ latest.get_label_display }}">{{ latest.status }}</span>
                            <div class="product_img">
                                <a href="{{ latest.get_absolute_url }}">
                                    {% for images in latest.get_second_image %}
                                        {% thumbnail images.product_image "330x283" crop="10px 10px"  as im %}
                                                <img  style="margin:{{ im|margin:"330x283" }}" src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}"  />
                                        {% endthumbnail %}
                                    {% endfor %}
                                </a>
                                <div class="product_action_box" id = "part{{ latest.id }}">
                                    {% if request.user.is_authenticated %}
                                        {% if request.user in latest.favourite.all %}
                                            {% csrf_token %}
                                             <ul class="list_none pr_action_btn">
                                                <li class="add-to-cart"><a href="#" id = "cart" data-id="{{ latest.id }}"><i class="icon-basket-loaded"></i> Add To Cart</a></li>
                                                <li><a href="#" id = "wishlist" data-id="{{ latest.id }}"><i class="fas fa-heart" style="color:red"></i></a></li>
                                            </ul>
                                        {% else %}
                                            <ul class="list_none pr_action_btn">
                                                <li class="add-to-cart"><a href="#" id = "cart" data-id="{{ latest.id }}"><i class="icon-basket-loaded"></i> Add To Cart</a></li>
                                                <li><a href="#" id = "wishlist" data-id="{{ latest.id }}"><i class="icon-heart"></i></a></li>
                                            </ul>
                                        {% endif %}
                                    {% else %}
                                        <ul class="list_none pr_action_btn">
                                                <li class="add-to-cart"><a href="{% url 'home:favourite_ad' id=latest.id %}" id = "cart" data-id="{{ latest.id }}"><i class="icon-basket-loaded"></i> Add To Cart</a></li>
                                                <li><a href="{% url 'home:favourite_ad' id=latest.id %}" id = "wishlist" data-id="{{ latest.id }}"><i class="icon-heart"></i></a></li>
                                            </ul>
                                    {% endif %}
                                </div>
                            </div>
                           <div class="product_info">
                                <h6 class="product_title"><a href="{{ latest.get_absolute_url }}">{{ latest.title }}</a></h6>
                                <div class="product_price">
                                    {% if latest.discount_price %}
                                        <span class="price">₦{{ latest.discount_price|intcomma}}</span>
                                        <del>₦{{ latest.price|intcomma}}</del>
                                     {% else %}
                                        <span class="price">₦{{ latest.price|intcomma}}</span>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
		</div>
    </div>
</div>
<!-- END SECTION SHOP -->

{% include 'subscribe.html' %}

</div>
<!-- END MAIN CONTENT -->

{% endblock %}

templates/home/special_section.html
{% if request.user.is_authenticated %}

    {% if request.user in ad.favourite.all %}
        {% csrf_token %}
        <ul class="list_none pr_action_btn">
            <li class="add-to-cart"><a href="#" id = "cart" data-id="{{ ad.id }}"><i class="icon-basket-loaded"></i> Add To Cart</a></li>
            <li><a href="#" id = "wishlist" data-id="{{ ad.id }}"><i class="fas fa-heart" style="color:red"></i></a></li>
        </ul>
    {% else %}
        <ul class="list_none pr_action_btn">
            <li class="add-to-cart"><a href="#" id = "cart" data-id="{{ ad.id }}"><i class="icon-basket-loaded"></i> Add To Cart</a></li>
            <li><a href="#" id = "wishlist" data-id="{{ ad.id }}"><i class="icon-heart"></i></a></li>
        </ul>
    {% endif %}
{% else %}
    <ul class="list_none pr_action_btn">
        <li class="add-to-cart"><a href="{{ ad.get_add_to_cart_url }}"><i class="icon-basket-loaded"></i> Add To Cart</a></li>
        <li><a href="{% url 'home:favourite_ad' id=ad.id %}"><i class="icon-heart"></i></a></li>
    </ul>
{% endif %}