blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.post_list, name='list'),
    path('create/', views.post_create, name='post_create'),
    path('(<id>\d+)/<slug>[\w-]+/', views.post_detail, name='post_detail'),
    path('<slug>[\w-]+/edit/', views.post_update, name='update'),
    path('<slug>[\w-]+/delete/', views.post_delete, name='post_delete'),

]

clothing/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('social-auth/',include('social_django.urls', namespace='social')),
    path('productcreate/',include('productCreate.urls', namespace='productcreate')),
    path('blog/',include('blog.urls', namespace='blog')),
    path('marketing/',include('marketing.urls', namespace='marketing')),
    path('',include('home.urls', namespace='home')),
    path('order/',include('order.urls', namespace='order')),
    path('owner/',include('owner.urls', namespace='owner')),
    path('product_search/',include('search.urls', namespace='product_search')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('tracking/', include('tracking.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    # path("paystack", include(('paystack.urls', 'paystack'), namespace='paystack')),
]
if settings.DEBUG:urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_list, name='home'),
    path('category_chart/', views.category_chart, name='category_chart'),
    path('ads_list', views.ads_list, name='ads_list'),
    path('allads_list', views.allads_list, name='allads_list'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('favourites/', views.ads_favourite_list, name="favourites"),
    path('favourite_ads/', views.favourite_ads, name="favourite_ads"),
    path('<slug:category_slug>/', views.ads_list, name='ads_list_by_category'),
    path('delete_post/(<pk>\d+)/', views.delete_post, name='delete_post'),
    path('<int:id>/favourite_ad/',views.favourite_ad, name='favourite_ad'),
    path('<int:id>/favourite_delete/',views.favourite_delete, name='favourite_delete'),
    path('<int:id>/<slug:slug>/', views.ad_detail, name='ad_detail'),
    path('category_count/',views.category_count,name='category_count'),
    path('ajax/load-subs/', views.load_subcategories, name='ajax_load_subs'),

]

search/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'search'

urlpatterns = [
    path('product_filter/',views.filter,name='product_filter'),
#    path('ajax_filter/',views.ajax_filter,name='ajax_filter'),

]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.db.models import Q, Count
from django.shortcuts import render, get_object_or_404
from productCreate.models import Products, Category, SubCategory,ProductSize
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect, Http404,HttpResponse, JsonResponse



def is_valid_queryparam(param):
    return param != '' and param is not None


def filter(request):
    qs = Products.objects.all()
    order = request.GET.get('order', '')
    # qs = qs.order_by(order)
    categories = Category.objects.all()
    subcategories = SubCategory.objects.all()
    sizes = ProductSize.objects.all()
    is_favourite = False
    title_contains_query = request.GET.get('title_contains_query')
    price_min = request.GET.get('price_min')
    price_max = request.GET.get('price_max')
    date_min = request.GET.get('date_min')
    date_max = request.GET.get('date_max')
    category = request.GET.get('category')
    size = request.GET.get('size')

    if is_valid_queryparam(title_contains_query):
        qs = qs.filter(Q(title__icontains=title_contains_query )
                       | Q(description__icontains=title_contains_query)
                       ).distinct()

    if is_valid_queryparam(price_min):
        qs = qs.filter(price__gte=price_min)

    if is_valid_queryparam(price_max):
        qs = qs.filter(price__lt=price_max)


    if is_valid_queryparam(date_min):
        qs = qs.filter(created_date__gte=date_min)

    if is_valid_queryparam(date_max):
        qs = qs.filter(created_date__lt=date_max)

    if is_valid_queryparam(category) and category != 'Choose...':
        qs = qs.filter(category__name=category)

    if is_valid_queryparam(size):
        qs = qs.filter(size__name=size)


    if order == "price":
        qs = qs.order_by(order)
    elif order == "-price":
        qs = qs.order_by(order)
    elif order == "-created_date":
        qs = qs.order_by(order)

    paginator = Paginator(qs, 2)  # Show 25 contacts per page
    page_request_var = "page"
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        'queryset': queryset,'categories': categories,'is_favourite': is_favourite,
        'order': order,'page': page,'subcategories':subcategories,'sizes':sizes
    }

    return render(request, "search/main_search.html", context)

templates/search/ajax_search.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
{% load thumbnail %}
{% load humanize %}
{% load hitcount_tags %}


{% for ad in queryset %}
<div class="property-listing property-1">

    <div class="listing-img-wrapper">
        {% for images in ad.get_first_image %}
            {% thumbnail images.ad_image "800x530" crop="10px 10px"  as im %}
                <a href="{{ ad.get_absolute_url }}">
                    <img  style="margin:{{ im|margin:"800x530" }}" src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}" class="img-fluid mx-auto" alt="" />
                </a>
            {% endthumbnail %}
        {% endfor %}
        <div class="listing-like-top" id = "part{{ ad.id }}">
            {% include 'home/favourite_section.html' %}
        </div>

        <div class="listing-rating">
            <i class="ti-star filled"></i>
            <i class="ti-star filled"></i>
            <i class="ti-star filled"></i>
            <i class="ti-star filled"></i>
            <i class="ti-star"></i>
        </div>
        <span class="property-type">{{ ad.property_offer }}</span>
    </div>

    <div class="listing-content">

        <div class="listing-detail-wrapper">

{#                                        <h6 class="">{{ ad.category }}</h6>#}
            <div class="listing-short-detail">
                <span class="listing-location" style="color: #00A877">{{ ad.category }}</span>
                <h4 class="listing-name"><a href="{{ ad.get_absolute_url }}">{{ ad.property_title }}</a></h4>
                <span class="listing-location"><i class="ti-location-pin"></i>{{ ad.address|truncatechars_html:50 }}</span>
            </div>
            <div class="list-author">
                <a href="#"><img src="{{ ad.profile.photo.url }}" class="img-circle avater-30" alt=""></a>
            </div>
        </div>

        <div class="listing-features-info">
            <ul>
                <li><strong>Bed:</strong>{{ ad.bedroom }}</li>
                <li><strong>Bath:</strong>{{ ad.bathroom }}</li>
                <li><strong>Sqft:</strong>{{ ad.property_area }}</li>
            </ul>
        </div>

        <div class="listing-footer-wrapper">
            <div class="listing-price">
                <h4 class="list-pr">₦{{ ad.property_price|intcomma}}</h4>
            </div>
            <div class="listing-detail-btn">
                <a href="{{ ad.get_absolute_url }}" class="more-btn">More Info</a>
            </div>
        </div>

    </div>

</div>
{% empty %}
    <div class="container-fluid">
        <h3 style="text-align:center;">No Property found </h3>
    </div>
{% endfor %}

templates/search/main_search.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
{% load thumbnail %}
{% load humanize %}
{% load hitcount_tags %}
{% load templatehelpers %}

{% block title %}Your search{% endblock %}

{% block content %}
    <!-- START SECTION BREADCRUMB -->
    <div class="breadcrumb_section bg_gray page-title-mini">
        <div class="container"><!-- STRART CONTAINER -->
            <div class="row align-items-center">
                <div class="col-md-6">
                    <div class="page-title">
                        <h6>Shop</h6>
                    </div>
                </div>
                <div class="col-md-6">
                    <ol class="breadcrumb justify-content-md-end">
                        {% if not category %}
                            <li class="breadcrumb-item"><a href="{% url "home:home" %}">Home</a></li>
                            <li class="breadcrumb-item">Shop list</li>
                        {% else %}
                            <li class="breadcrumb-item"><a href="{% url "home:home" %}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{% url "home:ads_list" %}">Shop list</a></li>
                            <li class="breadcrumb-item active">{{ category.name }}</li>
                        {% endif %}
                    </ol>
                </div>
            </div>
        </div><!-- END CONTAINER-->
    </div>
    <!-- END SECTION BREADCRUMB -->

    <!-- START MAIN CONTENT -->
    <div class="main_content">

    <!-- START SECTION SHOP -->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <div class="row align-items-center mb-4 pb-1">
                        <div class="col-12">
                            <div class="product_header">
                                <div class="product_header_left">
                                    <div class="dropdown ">
                                      <button class="btn btn-default dropdown-toggle" style="border-color:red" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Sort By
                                      </button>
                                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href={{ request.build_absolute_uri }}{% relative_url '-created_date' 'order' params %}>Latest Items</a>
                                        <a class="dropdown-item" href={{ request.build_absolute_uri }}{% relative_url '-price' 'order' params %}>High - Low Price</a>
                                        <a class="dropdown-item" href={{ request.build_absolute_uri }}{% relative_url 'price' 'order' params %}>Low - High Price</a>
                                      </div>
                                    </div>
                                </div>
                                <div class="product_header_right">
                                    <div class="products_view">
                                        <a href="javascript:Void(0);" class="shorting_icon grid active"><i class="ti-view-grid"></i></a>
                                    </div>
{#                                    <div class="products_view">#}
{#                                        {% with total_property=ads|length %}#}
{#                                            <p class="result-show-message">Showing {{ total_property }} result{{ total_property|pluralize }}</p>#}
{#                                        {% endwith %}#}
{#                                    </div>#}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row shop_container">
                        <div class="col-md-4 col-6">
                            {% for ad in queryset %}
                                <div class="product">
                                    <div class="product_img">
                                        <a href="{{ ad.get_absolute_url }}">
                                            <span class="{{ ad.get_label_display }}">{{ ad.status }}</span>
                                            {% for images in ad.get_second_image %}
                                                {% thumbnail images.product_image "255x283" crop="10px 10px"  as im %}
                                                    <a href="{{ ad.get_absolute_url }}">
                                                        <img  style="margin:{{ im|margin:"255x283" }}" src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}" class="" alt="" />
                                                    </a>
                                                {% endthumbnail %}
                                            {% endfor %}
                                        </a>
                                        <div class="product_action_box" id = "part{{ ad.id }}">
                                            {% include 'home/special_section.html' %}
                                        </div>
                                    </div>
                                    <div class="product_info">
                                        <h6 class="product_title"><a href="{{ ad.get_absolute_url }}">{{ ad.title }}</a></h6>
                                        <div class="product_price">
                                             {% if ad.discount_price %}
                                                <span class="price">₦{{ ad.discount_price|intcomma}}</span>
                                                <del>₦{{ ad.price|intcomma}}</del>
                                             {% else %}
                                                <span class="price">₦{{ ad.price|intcomma}}</span>
                                            {% endif %}
                                        </div>

                                        <div class="list_product_action_box">
                                            <ul class="list_none pr_action_btn" id = "part{{ ad.id }}">
                                                {% include 'home/special_section.html' %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            {% if queryset.has_other_pages %}
                              <ul class="pagination mt-3 justify-content-center pagination_style1">
                                {% if queryset.has_previous %}
                                  <li class="page-item"><a href="?page={{ queryset.previous_page_number }}" class="page-link"> <i class="linearicons-arrow-left"></i></a></li>
                                {% else %}
                                  <li class="page-item disabled"><a class="page-link"> <i class="linearicons-arrow-left"></i></a></li>
                                {% endif %}
                                {% for i in queryset.paginator.page_range %}
                                  {% if queryset.number == i %}
                                    <li class="page-item active"><a class="page-link"><span>{{ i }}<span class="sr-only">(current)</span></span></a></li>
                                  {% else %}
        {#                                    <li><a href="?page={{ i }}">{{ i }}</a></li>#}
                                    <li class="page-item"><a class="page-link" href={% relative_url i 'page' request.GET.urlencode %}>{{ i }}</a></li>
                                  {% endif %}
                                {% endfor %}
                                {% if queryset.has_next %}
                                  <li class="page-item"><a href="?page={{ queryset.next_page_number }}" class="page-link"><i class="linearicons-arrow-right"></i></a></li>
                                {% else %}
                                  <li class="page-item disabled"><a class="page-link"><i class="linearicons-arrow-right"></i></a></li>
                                {% endif %}
                              </ul>
                            {% endif %}
                        </div>
                    </div>
                </div>

               {% include 'search/sub_search.html' %}

            </div>
        </div>
    </div>
    <!-- END SECTION SHOP -->

    <!-- START SECTION SUBSCRIBE NEWSLETTER -->
    {% include 'subscribe.html' %}
    <!-- START SECTION SUBSCRIBE NEWSLETTER -->

    </div>
    <!-- END MAIN CONTENT -->
{% endblock %}

{% block script %}
    <script src="{% static 'assets/js/ads.js' %}" type="text/javascript"></script>
{% endblock %}

templates/search/other_search.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
{% load thumbnail %}


<div class="header-advance-search">
    <form method="GET" action="{% url 'product_search:product_filter' %}">
        <input type="text" name="title_contains_query" placeholder="Search your product">
        <button><span class="icon_search"></span></button>
    </form>
</div>

templates/search/sub_search.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
{% load thumbnail %}


 <div class="col-lg-3 order-lg-first mt-4 pt-2 mt-lg-0 pt-lg-0">
    <div class="sidebar">
        <form method="GET" action="{% url 'product_search:product_filter' %}" id="list_data" data-models-url="{% url 'home:ajax_load_subs' %}">
            <input type="hidden" name="order" value="{{ request.GET.order.strip }}"/>
            <div class="widget">
              <input type="text" name="title_contains_query" value="{{ request.GET.title_contains_query.strip }}"
                     placeholder="Search" class="form-control"/>
            </div>

            <div class="widget">
                <h5 class="widget_title">Categories</h5>
                    {% for category in categories %}
                    <div class="widget_categories">

                            <input type="radio" id="cat" {% if request.GET.category.strip == category.id|stringformat:"i" %}checked{% endif %} name="category" value="{{ category.id }}">
                            <label for="{{ category.name }}"><span class="categories_name">{{ category.name }}</span></label>

                    </div>
                    {% endfor %}
            </div>
            <div class="widget">
                <select class="form-control" id="sub" name="subcategory">
{#                    {% if request.GET.category.strip == ' ' %}#}
                        <option value="Select Subcategory" disabled selected>SubCategories</option>
{#                    {% else %}#}
                        {% for subcategory in subcategories %}
                          <option value="{{ subcategory.name }}" {% if request.GET.subcategory.strip == subcategory.name %}selected{% endif %} >{{ subcategory }}</option>
                        {% endfor %}
{#                    {% endif %}#}
                </select>
            </div>

            <div class="widget">
                <h5 class="widget_title">Filter</h5>
                <div class="filter_price">
                     <div id="price-range"></div>
                     <div class="price_range">
                         <span>Price: <span id="flt_price"></span></span>
{#                         <input type="text" id="price-amount" readonly>#}
                         <input type="hidden" name="price_min" id="txtMin" value="{{ request.GET.price_min.strip }}"/>
                         <input type="hidden" name="price_max" id="txtMax" value="{{ request.GET.price_max.strip }}"/>
                     </div>
                 </div>
            </div>

            <div class="widget">
                <h5 class="widget_title">Size</h5>
                <select class="form-control" id="siz" name="size">

                        <option value="Select Size" disabled selected>Size</option>
                        {% for size in sizes %}
                          <option value="{{ size.name  }}" {% if request.GET.size.strip == size.name  %}selected{% endif %} >{{ size }}</option>
                        {% endfor %}

                </select>

{#                {% for size in sizes %}#}
{#                     <div class="product_size_switch">#}
{#                        <span>#}
{#                            <input type="radio" id="{{ size.name }}" {% if size.name == request.GET.size.strip %}checked{% endif %} name="size" value="{{ size.name }}">#}
{#                            <label for="{{ size.name }}">{{ size.name }} </label>#}
{#                        </span>#}
{#                    </div>#}
{#                {% endfor %}#}

            </div>

            <div class="widget">
                <button class="btn btn-fill-out" title="Submit Your Message!" type="submit">Submit</button>
            </div>
        </form>
    </div>
</div>