blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.post_list, name='list'),
    path('create/', views.post_create, name='post_create'),
    path('(<id>\d+)/<slug>[\w-]+/', views.post_detail, name='post_detail'),
    path('<slug>[\w-]+/edit/', views.post_update, name='update'),
    path('<slug>[\w-]+/delete/', views.post_delete, name='post_delete'),

]

cart/urls.py
from django.urls import path
from . import views
from .views import (
    OrderSummaryView
)


app_name = 'cart'

urlpatterns = [

  path('', views.cart_detail, name='cart_detail'),
  path('add/<int:product_id>/',views.cart_add,name='cart_add'),
  path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
  path('add_to_cart/<slug>/', views.add_to_cart, name='add_to_cart'),
  path('add_to_cart_ajax/', views.add_to_cart_ajax, name='add_to_cart_ajax'),
  path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
#    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
  path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove_from_cart'),
  path('remove_item_from_cart/<slug>/', views.remove_single_item_from_cart,
         name='remove_single_item_from_cart'),

]

clothing/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('social-auth/',include('social_django.urls', namespace='social')),
    path('productcreate/',include('productCreate.urls', namespace='productcreate')),
    path('blog/',include('blog.urls', namespace='blog')),
    path('marketing/',include('marketing.urls', namespace='marketing')),
    path('',include('home.urls', namespace='home')),
    path('order/',include('order.urls', namespace='order')),
    path('owner/',include('owner.urls', namespace='owner')),
    path('product_search/',include('search.urls', namespace='product_search')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('tracking/', include('tracking.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    # path("paystack", include(('paystack.urls', 'paystack'), namespace='paystack')),
]
if settings.DEBUG:urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_list, name='home'),
    path('category_chart/', views.category_chart, name='category_chart'),
    path('ads_list', views.ads_list, name='ads_list'),
    path('allads_list', views.allads_list, name='allads_list'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('favourites/', views.ads_favourite_list, name="favourites"),
    path('favourite_ads/', views.favourite_ads, name="favourite_ads"),
    path('<slug:category_slug>/', views.ads_list, name='ads_list_by_category'),
    path('delete_post/(<pk>\d+)/', views.delete_post, name='delete_post'),
    path('<int:id>/favourite_ad/',views.favourite_ad, name='favourite_ad'),
    path('<int:id>/favourite_delete/',views.favourite_delete, name='favourite_delete'),
    path('<int:id>/<slug:slug>/', views.ad_detail, name='ad_detail'),
    path('category_count/',views.category_count,name='category_count'),
    path('ajax/load-subs/', views.load_subcategories, name='ajax_load_subs'),

]

order/urls.py
from django.urls import path

from . import views
from .views import (
    CheckoutView,
    PaymentView,
)

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),  # <-- this one here
    path('order_all/', views.order_all, name='order_all'),
    path('order_owner/', views.order_owner, name='order_owner'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('transfer/', views.transfer, name='transfer'),
    path('payment_confirm/', views.payment_confirm, name='payment_confirm'),
]

owner/urls.py
from django.urls import path
from . import views

app_name = 'owner'

urlpatterns = [
    path('my_cart/', views.my_cart, name='my_cart'),
    path('bookmarked/', views.bookmarked, name='bookmarked'),
    path('delete_post/(<pk>\d+)/', views.delete_post, name='delete_post'),
    path('hide_post/(<pk>\d+)/', views.hide_post, name='hide_post'),
    path('create_contact/', views.create_contact, name='create_contact'),
    path('about_us/', views.about_us, name='about_us'),
    path('faq/', views.faq, name='faq'),
    path('terms_conditions/', views.terms_conditions, name='terms_conditions'),
    path('privacy/', views.privacy, name='privacy'),
    path('success/', views.success, name='success'),
    path('failure/', views.failure, name='failure'),

]

templates/base.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
{% load bootstrap4 %}
{% load thumbnail %}
{% load humanize %}
<html lang="en">

<head>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="Anil z" name="author">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Shopwise is Powerful features and You Can Use The Perfect Build this Template For Any eCommerce Website. The template is built for sell Fashion Products, Shoes, Bags, Cosmetics, Clothes, Sunglasses, Furniture, Kids Products, Electronics, Stationery Products and Sporting Goods.">
    <meta name="keywords" content="ecommerce, electronics store, Fashion store, furniture store,  bootstrap 4, clean, minimal, modern, online store, responsive, retail, shopping, ecommerce store">

    <!-- SITE TITLE -->
    <title>{% block title %}Stardom{% endblock %}</title>
    <!-- Favicon Icon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/images/favicon.png' %}">
    <!-- Animation CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
    <!-- Latest Bootstrap min CSS -->
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800,900&amp;display=swap" rel="stylesheet">
    <!-- Icon Font CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/simple-line-icons.css' %}">
    <!--- owl carousel CSS-->
    <link rel="stylesheet" href="{% static 'assets/owlcarousel/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/owlcarousel/css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'assets/owlcarousel/css/owl.theme.default.min.css' %}">
    <!-- Magnific Popup CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.css' %}">
    <!-- Slick CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick-theme.css' %}">
    <!-- Style CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">

</head>

<body>

    <!-- LOADER -->
    <div class="preloader">
        <div class="lds-ellipsis">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
    <!-- END LOADER -->
	{% include 'navbar.html' %}


{#    {% if messages %}#}
{#        <ul class="messages">#}
{#            {% for message in messages %}#}
{#            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}<a href="#" class="close">x</a></li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    {% endif %}#}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}


    {% block content %}

    {% endblock %}


    {% include 'footer.html' %}

	<a href="#" class="scrollup" style="display: none;"><i class="ion-ios-arrow-up"></i></a>

	<!-- Latest jQuery -->
    <script src="{% static 'assets/js/jquery-1.12.4.min.js' %}"></script>
    <!-- popper min js -->
    <script src="{% static 'assets/js/jquery-ui.js' %}"></script>
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <!-- Latest compiled and minified Bootstrap -->
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- owl-carousel min js  -->
    <script src="{% static 'assets/owlcarousel/js/owl.carousel.min.js' %}"></script>
    <!-- magnific-popup min js  -->
    <script src="{% static 'assets/js/magnific-popup.min.js' %}"></script>
    <!-- waypoints min js  -->
    <script src="{% static 'assets/js/waypoints.min.js' %}"></script>
    <!-- parallax js  -->
    <script src="{% static 'assets/js/parallax.js' %}"></script>
    <!-- countdown js  -->
    <script src="{% static 'assets/js/jquery.countdown.min.js' %}"></script>
    <!-- fit video  -->
    <script src="{% static 'assets/js/Hoverparallax.min.js' %}"></script>
    <!-- jquery.countTo js  -->
    <script src="{% static 'assets/js/jquery.countTo.js' %}"></script>
    <!-- imagesloaded js -->
    <script src="{% static 'assets/js/imagesloaded.pkgd.min.js' %}"></script>
    <!-- isotope min js -->
    <script src="{% static 'assets/js/isotope.min.js' %}"></script>
    <!-- jquery.appear js  -->
    <script src="{% static 'assets/js/jquery.appear.js' %}"></script>
    <!-- jquery.parallax-scroll js -->
    <script src="{% static 'assets/js/jquery.parallax-scroll.js' %}"></script>
    <!-- jquery.dd.min js -->
    <script src="{% static 'assets/js/jquery.dd.min.js' %}"></script>
    <!-- slick js -->
    <script src="{% static 'assets/js/slick.min.js' %}"></script>
    <!-- elevatezoom js -->
    <script src="{% static 'assets/js/jquery.elevatezoom.js' %}"></script>
    <!-- scripts js -->
    <script src="{% static 'assets/js/scripts.js' %}"></script>
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script src="{% static 'hitcount/hitcount-jquery.js' %}"></script>
     <script type="text/javascript">
          $(document).ready(function(event){
              $('#delete').click(function(){
              return confirm("Are you sure to delete this post?");
            });

             $('.reply-btn').click(function() {
              $(this).parent().parent().next('.replied-comments').fadeToggle()
            });

             $(document).on('submit', '.comment-form', function(event){
              event.preventDefault();
              console.log($(this).serialize());
              $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                dataType: 'json',
                success: function(response) {
                  $('.main-comment-section').html(response['form']);
                  $('textarea').val('');
                  $('.reply-btn').click(function() {
                    $(this).parent().parent().next('.replied-comments').fadeToggle();
                    $('textarea').val('');
                  });
                },
                error: function(rs, e) {
                  console.log(rs.responseText);
                },
              });
            });


            $(document).on('submit', '.reply-form', function(event){
              event.preventDefault();
              console.log($(this).serialize());
              $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                dataType: 'json',
                success: function(response) {
                  $('.main-comment-section').html(response['form']);
                  $('textarea').val('');
                  $('.reply-btn').click(function() {
                    $(this).parent().parent().next('.replied-comments').fadeToggle();
                    $('textarea').val('');
                  });
                },
                error: function(rs, e) {
                  console.log(rs.responseText);
                },
              });
            });

           $(document).on('click', '#wishlist', function(event){
              event.preventDefault();
              var pk = $(this).data('id');
              var check = pk;
              $.ajax({
                type: 'POST',
                url: '{% url 'home:favourite_ads'%}',
                data: {'id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                dataType: 'json',
                success: function(response){
                    $('#part' + check).html(response['form']);
                  {#console.log($('#part' + check).html(response['form']));#}
                },
                error: function(rs, e){
                  console.log(rs.responseText);
                },
              });
            });

           $(document).on('click', '#cart', function(event){
              event.preventDefault();
              var pk = $(this).data('id');
              var check = pk;
              $.ajax({
                type: 'POST',
                url: '{% url 'cart:add_to_cart_ajax'%}',
                data: {'id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                dataType: 'json',
                success: function(data){
                    if (data['status'] == 'ok') {
                        alert('This item quantity was updated');
                        $('#part' + check).html(response['ok']);
                    }
                    elseif:
                     if (data['status'] == 'ook') {
                        alert('This item was added to your cart');
                        $('#part' + check).html(response['ok']);
                    }
                    elseif:
                     if (data['status'] == 'ko') {
                        alert('This item was added to your cart');
                        $('#part' + check).html(response['ok']);
                    }
                },
                error: function(rs, e){
                  console.log(rs.responseText);
                },
              });
            });

           {#$(document).ready(function() {#}
           {#   $.ajaxSetup({ cache: false }); // This part addresses an IE bug.  without it, IE will only load the first number and will never refresh#}
           {#   var pathname = window.location.pathname;#}
           {#   var my_refresh = setInterval(function() {#}
           {#     $('#carts').load(pathname);#}
           {#   }, 10000); // the "1000"#}
           {# });#}


           {#$(document).on('click', '#sort', function(event){#}
           {#     var latest = $(this).data('latest');#}
           {#     var descending = $(this).data('descending');#}
           {#     var ascending = $(this).data('ascending');#}
           {#     $.ajax({#}
           {#         url:'{% url 'search:filter'%}',#}
           {#         method:"POST",#}
           {#         data:{latest:latest, descending:descending, ascending:ascending ,'csrfmiddlewaretoken': '{{ csrf_token }}'},#}
           {#         dataType: 'json',#}
           {#         success:function(data){#}
           {#             $('.filter_data').html(data);#}
           {#         }#}
           {#     });#}
           {# });#}

          });

        </script>

        <script>
            $("#cat").change(function () {
              var url = $("#list_data").attr("data-models-url");  // get the url of the `load_cities` view
              var catId = $(this).val();  // get the selected country ID from the HTML input

              $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                data: {
                  'category': catId       // add the country id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_cities` view function
                  $("#sub").html(data);  // replace the contents of the city input with the data that came from the server
                }
              });
            });
        </script>

        {% block script %}

        {% endblock %}
        {% block favourite %}

        {% endblock %}
        {% block extra_scripts %}

        {% endblock %}

</body>


<!-- Mirrored from demo.hasthemes.com/greenfarm-preview/greenfarm/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 18 Dec 2019 09:59:31 GMT -->
</html>

templates/footer.html
{% load static %}

<!-- START FOOTER -->
<footer class="footer_dark">
	<div class="footer_top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-12">
                	<div class="widget">
                        <div class="footer_logo">
                            <a href="#"><img src="{% static 'assets/images/logo_light.png' %}" alt="logo"/></a>
                        </div>
                        <p>If you are going to use of Lorem Ipsum need to be sure there isn't hidden of text</p>
                    </div>
                    <div class="widget">
                        <ul class="social_icons social_white">
                            <li><a href="#"><i class="ion-social-facebook"></i></a></li>
                            <li><a href="#"><i class="ion-social-twitter"></i></a></li>
                            <li><a href="#"><i class="ion-social-googleplus"></i></a></li>
                            <li><a href="#"><i class="ion-social-youtube-outline"></i></a></li>
                            <li><a href="#"><i class="ion-social-instagram-outline"></i></a></li>
                        </ul>
                    </div>
        		</div>
                <div class="col-lg-3 col-md-3 col-sm-6">
                	<div class="widget">
                        <h6 class="widget_title">Useful Links</h6>
                        <ul class="widget_links">
                            <li><a href="{% url "owner:about_us" %}">About Us</a></li>
                            <li><a href="{% url "owner:faq" %}">FAQ</a></li>
{#                            <li><a href="{% url 'blog:list' %}">Blog</a></li>#}
                            <li><a href="{% url "owner:create_contact" %}">Contact</a></li>
                            <li><a href="{% url 'owner:terms_conditions' %}">Terms & Conditions</a></li>
                            <li><a href="{% url "owner:privacy" %}">Privacy Policy</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                	<div class="widget">
                        <h6 class="widget_title">My Account</h6>
                        <ul class="widget_links">
                            <li><a href="{% url "profile_display" %}">My Account</a></li>
                            <li><a href="{% url "home:favourites" %}">Wishlist</a></li>
                            <li><a href="{% url 'cart:order-summary' %}">Cart</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-4 col-sm-6">
                	<div class="widget">
                        <h6 class="widget_title">Contact Info</h6>
                        <ul class="contact_info contact_info_light">
                            <li>
                                <i class="ti-location-pin"></i>
                                <p>123 Street, Old Trafford, New South London , UK</p>
                            </li>
                            <li>
                                <i class="ti-email"></i>
                                <a href="mailto:info@sitename.com">info@sitename.com</a>
                            </li>
                            <li>
                                <i class="ti-mobile"></i>
                                <p>+ 457 789 789 65</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom_footer border-top-tran">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p class="mb-md-0 text-center text-md-left">© {%now "Y"%} All Rights Reserved by Rockflint</p>
                </div>
                <div class="col-md-6">
                    <ul class="footer_payment text-center text-lg-right">
                        <li><img src="{% static 'assets/images/visa.png' %}" alt="visa"></li>
                        <li><img src="{% static 'assets/images/discover.png' %}" alt="discover"></li>
                        <li><img src="{% static 'assets/images/master_card.png' %}" alt="master_card"></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- END FOOTER -->

templates/footer_admin.html
{% load static %}

 <footer class="footer">
  <div class="row">
    <div class="col-md-6 col-sm-6 font-12">© {%now "Y"%} All Rights Reserved by Rockflint</div>
  </div>
</footer>

templates/navbar.html
{% load static %}
{% load cart_template_tags %}

<!-- START HEADER -->
<header class="header_wrap fixed-top header_with_topbar">
    <div class="middle-header dark_skin">
    	<div class="container">
        	<div class="nav_block">
                <a class="navbar-brand" href="{% url "home:home" %}">
                    <img class="logo_light" src="{% static 'assets/images/logo_light.png' %}" alt="logo" />
                    <img class="logo_dark" src="{% static 'assets/images/logo_dark.png' %}" alt="logo" />
                </a>
                <div class="product_search_form">
                    <form method="GET" action="{% url 'product_search:product_filter' %}">
                        {% csrf_token %}
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="custom_select">
                                    <select id="categories" name="category" class="first_null">
                                        <option value="" disabled selected hidden>All Category</option>
                                        {% for cat in categories %}
                                          <option value="{{ cat }}">{{ cat }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <input class="form-control" name="title_contains_query" placeholder="Search Product..." type="text">
                            <button type="submit" class="search_btn"><i class="linearicons-magnifier"></i></button>
                        </div>
                    </form>
                </div>
                 <ul class="navbar-nav attr-nav align-items-left">
                    <li class="pr_search_icon"><a href="javascript:void(0);" class="nav-link pr_search_trigger"><i class="linearicons-magnifier"></i></a></li>
                    <li class="dropdown">
                        {% if user.is_authenticated %}
                            <a data-toggle="dropdown" class="nav-link dropdown-toggle" href="#"><i class="linearicons-user"></i> <b>{{ request.user.first_name }}</b></a>
                            <div class="dropdown-menu">
                               <ul>
                                    {% if user.is_superuser %}
                                    <li class="dropdown-item "><a href="{% url "home:dashboard" %}">Dashboard</a></li>
                                    {% endif %}
                                    <li class="dropdown-item "><a href="{% url "profile_display" %}">Profile</a></li>
                                    <li class="dropdown-item "><a href="{% url "password_change" %}">Change Password</a></li>
                                    <hr class="solid" style="border-top: 3px solid #bbb">
                                    <li class="dropdown-item "><a href="{% url "logout" %}">Logout</a></li>
                                </ul>
                            </div>
                        {% endif %}
                    </li>
{#                    <li><a href="#" class="nav-link"><i class="linearicons-user"></i></a></li>#}
                    {% if user.is_authenticated %}
                         <li><a href="{% url "home:favourites" %}" class="nav-link"><i class="linearicons-heart"></i><span class="wishlist_count">{{ request.user|wish_item_count }}</span></a></li>
                        <li><a class="nav-link cart_trigger" href="{% url 'cart:order-summary' %}"><i class="linearicons-cart"></i><span class="cart_count">{{ request.user|cart_item_count }}</span></a></li>
                    {% else %}
                        <li><a href="{% url "login" %}" class="nav-link"><span><b>Login</b></span></a></li>
                        <li><a href="{% url "register" %}" class="nav-link"><span><b>Register</b></span></a></li>
                        <li><a href="{% url "home:favourites" %}" class="nav-link"><i class="linearicons-heart"></i><span class="wishlist_count">0</span></a></li>
                       <li><a class="nav-link cart_trigger" href="{% url 'cart:order-summary' %}"><i class="linearicons-cart"></i><span class="cart_count">0</span></a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</header>
<!-- END HEADER -->

templates/sidebar_admin.html
{% load static %}

<aside class="left-sidebar">
<!-- Sidebar scroll-->
<div class="scroll-sidebar">
  <!-- Sidebar navigation-->
  <nav class="sidebar-nav">
    <ul id="sidebarnav">
      <li> <a class="waves-effect waves-dark" aria-expanded="false"><i class="mdi mdi-cart-outline mr-10"></i><span class="hide-menu">Seafood Admin</span></a></li>
      {% if user.is_superuser %}
          <li> <a class="waves-effect waves-dark" href="{% url "home:dashboard" %}"> <i class="ti-angle-right"></i> <span class="hide-menu">Dashboard</span></a></li>
          <li> <a class="waves-effect waves-dark" href="{% url 'admin:index' %}"> <i class="ti-angle-right"></i> <span class="hide-menu">Admin</span></a></li>
          <li> <a class="waves-effect waves-dark" href="{% url "order:order_all" %}"> <i class="ti-angle-right"></i> <span class="hide-menu"> Order Status </span></a></li>
          <li> <a class="waves-effect waves-dark" href="{% url "order:order_owner" %}"> <i class="ti-angle-right"></i> <span class="hide-menu"> My Orders </span></a></li>
          <li><a class="waves-effect waves-dark" href="{% url "home:allads_list" %}"> <i class="ti-angle-right"></i> <span class="hide-menu">Product List </span></a></li>
          <li><a class="waves-effect waves-dark" href="{% url "productcreate:post" %}"> <i class="ti-angle-right"></i> <span class="hide-menu">Add Product</span></a></li>
          <li><a class="waves-effect waves-dark" href="{% url "home:customer_list" %}"> <i class="ti-angle-right"></i> <span class="hide-menu">View Customers</span></a></li>
      {% else %}
          <li> <a class="waves-effect waves-dark" href="{% url "home:dashboard" %}"> <i class="ti-angle-right"></i> <span class="hide-menu">Dashboard</span></a></li>
          <li> <a class="waves-effect waves-dark" href="{% url "order:order_owner" %}"> <i class="ti-angle-right"></i> <span class="hide-menu"> My Orders </span></a></li>
      {% endif %}
    </ul>
  </nav>
  <!-- End Sidebar navigation -->
</div>
<!-- End Sidebar scroll-->
</aside>

templates/subscribe.html
<!-- START SECTION SUBSCRIBE NEWSLETTER -->
<div class="section bg_default small_pt small_pb">
	<div class="container">
    	<div class="row align-items-center">
            <div class="col-md-6">
                <div class="heading_s1 mb-md-0 heading_light">
                    <h3>Subscribe Our Newsletter</h3>
                </div>
            </div>
            <div class="col-md-6">
                <div class="newsletter_form">
                    <form method="POST" action="{% url 'marketing:email-list-signup' %}">
                        {% csrf_token %}
                        <input type="text" required="" name="email" class="form-control rounded-0" placeholder="Enter Email Address">
                        <button type="submit" class="btn btn-dark rounded-0" name="submit" value="Submit">Subscribe</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- START SECTION SUBSCRIBE NEWSLETTER -->