blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.post_list, name='list'),
    path('create/', views.post_create, name='post_create'),
    path('(<id>\d+)/<slug>[\w-]+/', views.post_detail, name='post_detail'),
    path('<slug>[\w-]+/edit/', views.post_update, name='update'),
    path('<slug>[\w-]+/delete/', views.post_delete, name='post_delete'),

]

cart/urls.py
from django.urls import path
from . import views
from .views import (
    OrderSummaryView
)


app_name = 'cart'

urlpatterns = [

  path('', views.cart_detail, name='cart_detail'),
  path('add/<int:product_id>/',views.cart_add,name='cart_add'),
  path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
  path('add_to_cart/<slug>/', views.add_to_cart, name='add_to_cart'),
  path('add_to_cart_ajax/', views.add_to_cart_ajax, name='add_to_cart_ajax'),
  path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
#    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
  path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove_from_cart'),
  path('remove_item_from_cart/<slug>/', views.remove_single_item_from_cart,
         name='remove_single_item_from_cart'),

]

clothing/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('social-auth/',include('social_django.urls', namespace='social')),
    path('productcreate/',include('productCreate.urls', namespace='productcreate')),
    path('blog/',include('blog.urls', namespace='blog')),
    path('marketing/',include('marketing.urls', namespace='marketing')),
    path('',include('home.urls', namespace='home')),
    path('order/',include('order.urls', namespace='order')),
    path('owner/',include('owner.urls', namespace='owner')),
    path('product_search/',include('search.urls', namespace='product_search')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('tracking/', include('tracking.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    # path("paystack", include(('paystack.urls', 'paystack'), namespace='paystack')),
]
if settings.DEBUG:urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_list, name='home'),
    path('category_chart/', views.category_chart, name='category_chart'),
    path('ads_list', views.ads_list, name='ads_list'),
    path('allads_list', views.allads_list, name='allads_list'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('favourites/', views.ads_favourite_list, name="favourites"),
    path('favourite_ads/', views.favourite_ads, name="favourite_ads"),
    path('<slug:category_slug>/', views.ads_list, name='ads_list_by_category'),
    path('delete_post/(<pk>\d+)/', views.delete_post, name='delete_post'),
    path('<int:id>/favourite_ad/',views.favourite_ad, name='favourite_ad'),
    path('<int:id>/favourite_delete/',views.favourite_delete, name='favourite_delete'),
    path('<int:id>/<slug:slug>/', views.ad_detail, name='ad_detail'),
    path('category_count/',views.category_count,name='category_count'),
    path('ajax/load-subs/', views.load_subcategories, name='ajax_load_subs'),

]

order/urls.py
from django.urls import path

from . import views
from .views import (
    CheckoutView,
    PaymentView,
)

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),  # <-- this one here
    path('order_all/', views.order_all, name='order_all'),
    path('order_owner/', views.order_owner, name='order_owner'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('transfer/', views.transfer, name='transfer'),
    path('payment_confirm/', views.payment_confirm, name='payment_confirm'),
]

owner/urls.py
from django.urls import path
from . import views

app_name = 'owner'

urlpatterns = [
    path('my_cart/', views.my_cart, name='my_cart'),
    path('bookmarked/', views.bookmarked, name='bookmarked'),
    path('delete_post/(<pk>\d+)/', views.delete_post, name='delete_post'),
    path('hide_post/(<pk>\d+)/', views.hide_post, name='hide_post'),
    path('create_contact/', views.create_contact, name='create_contact'),
    path('about_us/', views.about_us, name='about_us'),
    path('faq/', views.faq, name='faq'),
    path('terms_conditions/', views.terms_conditions, name='terms_conditions'),
    path('privacy/', views.privacy, name='privacy'),
    path('success/', views.success, name='success'),
    path('failure/', views.failure, name='failure'),

]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

order/forms.py
from django import forms
from .models import Order
from .models import State,Lga

class OrderCreateForm(forms.ModelForm):
    ref_code = forms.CharField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)
    class Meta:
        model = Order
        fields = ['ref_code']

PAYMENT_CHOICES = (
    ('T', 'Transfer'),
    ('0', 'Online Payment')
)

class CheckoutForm(forms.Form):
    street_address = forms.CharField()
    apartment_address = forms.CharField(required=False)
    same_billing_address = forms.BooleanField(required=False,widget=forms.CheckboxInput())
    save_info = forms.BooleanField(required=False,widget=forms.CheckboxInput())
    state = forms.ModelChoiceField(queryset=State.objects.all(), to_field_name='id')
    city = forms.ModelChoiceField(queryset=Lga.objects.all(), to_field_name='id')
    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = Lga.objects.none()

        if 'state' in self.data:
            try:
                state_id = int(self.data.get('state'))
                self.fields['city'].queryset = Lga.objects.filter(state_id=state_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        # elif self.instance.pk:
        #     self.fields['city'].queryset = self.instance.state.city.order_by('name')

owner/forms.py
from django import forms

from .models import Information

class InformationForm(forms.ModelForm):
    # content = forms.TextField(required = True)

    class Meta:
        model = Information
        fields = ('name','subject','email','message')

cart/views.py
from django.conf import settings
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.views.generic import ListView, DetailView, View
from productCreate.models import Products
from order.models import Order,OrderItem
from .cart import Cart
from .forms import CartAddProductForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.http import HttpResponseRedirect, Http404,HttpResponse, JsonResponse



@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    # products = []
    # for item in cart:
    #     item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
    #                                                                'update': True})
        # products.append(item)
    context = {'cart': cart}
    # context['products'] = products
    return render(request, 'owner/cart.html', context)


class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, is_ordered=False)
            context = {
                'cart': order
            }
            return render(self.request, 'owner/cart.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/")

@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Products, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        is_ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, is_ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "This item quantity was updated.")
            return HttpResponseRedirect(item.get_absolute_url())
        else:
            order.items.add(order_item)
            messages.info(request, "This item was added to your cart.")
            return HttpResponseRedirect(item.get_absolute_url())
    else:
        order = Order.objects.create(
            user=request.user)
        order.items.add(order_item)
        messages.info(request, "This item was added to your cart.")
        return HttpResponseRedirect(item.get_absolute_url())

@login_required
def add_to_cart_ajax(request):
    item = get_object_or_404(Products,id=request.POST.get('id'))
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        is_ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, is_ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__id=item.id).exists():
            order_item.quantity += 1
            order_item.save()
            return JsonResponse({'status':'ok'})
        else:
            order.items.add(order_item)
            return JsonResponse({'status':'ook'})
    else:
        order = Order.objects.create(
            user=request.user)
        order.items.add(order_item)
        messages.info(request, "This item was added to your cart.")
        return JsonResponse({'status':'ko'})


@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Products, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        is_ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                is_ordered=False
            )[0]
            order.items.remove(order_item)
            messages.info(request, "This item was removed from your cart.")
            return redirect("cart:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("home:ad_detail", slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("home:ad_detail", slug=slug)


@login_required
def remove_single_item_from_cart(request, slug):
    item = get_object_or_404(Products, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        is_ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                is_ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request, "This item quantity was updated.")
            return redirect("cart:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("core:product", slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("core:product", slug=slug)

owner/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from account.models import Profile
from productCreate.models import Products, ProductsImages, Category, SubCategory
from django.db.models import Q
from django.db.models import Count
from django.http import HttpResponseRedirect, Http404,HttpResponse, JsonResponse
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import InformationForm
from django.core.mail import send_mail
import random

@login_required
def my_cart(request):
    myab_list = Products.objects.filter(profile__user=request.user)
    profile = Profile.objects.get(user=request.user)
    ads = Products.objects.filter(active=True)
    lates = Products.objects.all().order_by('-created_date')[:3]
    counts = Products.objects.all().values('category__name').annotate(total=Count('category'))

    paginator = Paginator(myab_list, 6)  # Show 25 contacts per page
    page_request_var = "page"
    page = request.GET.get('page')
    try:
        myab = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        myab = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        myab = paginator.page(paginator.num_pages)
    return render(request, 'owner/cart.html', {'myab': myab, 'profile': profile, 'ads': ads, 'lates': lates,
                                                 'counts': counts, 'page_request_var': page_request_var})



def bookmarked(request):
    return render(request, 'owner/bookmarked.html', {})

@login_required
def delete_post(request,pk=None):
    ad = Products.objects.get(id=pk)
    if request.user != ad.profile.user:
        raise Http404()
    ad.is_active = False
    messages.success(request, "Successfuly deleted")
    return redirect('home:allads_list')


@login_required
def hide_post(request,pk=None):
    ad = Products.objects.get(id=pk)
    if request.user != ad.profile.user:
        raise Http404()
    ad.is_active = False
    messages.success(request, "You property has been successfuly deleted")
    return redirect('home:allads_list')

def create_contact(request):
    if request.POST:
        form = InformationForm(request.POST)
        if form.is_valid():
            post_info = form.save(commit=False)
            # post.user = request.user
            post = form.cleaned_data
            subject = post['subject']
            message ='Hello "{}" sent you a message below \n{}'.format( post['name'], post['message'])
            sender = post['email']
            to = ['ezechdr16@gmail.com']
            send_mail(subject, message, sender, to)
            post_info.save()

            # text = form.cleaned_data['headline','content']
            messages.add_message(request, messages.SUCCESS, 'Your message has been recieved')
            form = InformationForm()
            return redirect('others:create_contact')

    else:
        form = InformationForm()

        args = {'form': form}
        return render(request, 'owner/others/contact.html', args)

def about_us(request):
    return render(request, 'owner/others/about.html', )

def faq(request):
    return render(request, 'owner/others/faq.html', )

def terms_conditions(request):
    return render(request, 'owner/others/terms.html', )

def privacy(request):
    return render(request, 'owner/others/privacy.html', )

def success(request):
    return render(request, 'paystack/success-page.html',)

def failure(request):
    return render(request, 'paystack/failed-page.html',)

templates/owner/bookmarked.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
{% load thumbnail %}
{% load humanize %}

{% block title %}Bookmarked property{% endblock %}

{% block content %}
  <!-- START SECTION BREADCRUMB -->
<div class="breadcrumb_section bg_gray page-title-mini">
    <div class="container"><!-- STRART CONTAINER -->
        <div class="row align-items-center">
        	<div class="col-md-6">
                <div class="page-title">
            		<h6>Wishlist</h6>
                </div>
            </div>
            <div class="col-md-6">
                <ol class="breadcrumb justify-content-md-end">
                    <li class="breadcrumb-item"><a href="{% url "home:home" %}">Home</a></li>
                    <li class="breadcrumb-item active">Wishlist</li>
                </ol>
            </div>
        </div>
    </div><!-- END CONTAINER-->
</div>
<!-- END SECTION BREADCRUMB -->

<!-- START MAIN CONTENT -->
<div class="main_content">

<!-- START SECTION SHOP -->
<div class="section">
	<div class="container">
        <div class="row">
            <div class="col-12">
                <div class="table-responsive wishlist_table">
                	<table class="table">
                    	<thead>
                        	<tr>
                            	<th class="product-thumbnail">Image</th>
                                <th class="product-name">Product</th>
                                <th class="product-price">Price</th>
                                <th class="product-stock-status">Stock Status</th>
                                <th class="product-add-to-cart"></th>
                                <th class="product-remove">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for p in favourite_posts %}
                        	<tr>
                            	<td class="product-thumbnail">
                                    {% for images in p.get_second_image %}
                                        {% thumbnail images.product_image "100x111" crop="10px 10px"  as im %}
                                        <a href="{{ p.get_absolute_url }}">
                                            <img   src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}" class=""  />
                                        </a>
                                        {% endthumbnail %}
                                    {% endfor %}
                                </td>
                                <td class="product-name" data-title="Product"><a href="{{ p.get_absolute_url }}">{{p.title}}</a></td>
                                <td class="product-price" data-title="Price">₦{{ p.price|intcomma}}</td>
                                <td class="product-stock-status" data-title="Stock Status"><span class="badge badge-pill badge-success">{{p.status}}</span></td>
                                <td class="product-add-to-cart">
                                    {% if request.user.is_authenticated %}
                                        {% csrf_token %}
                                        <a href="#" id = "cart" data-id="{{ p.id }}" class="btn btn-fill-out"><i class="icon-basket-loaded"></i><span class="hidden-xs">&nbsp; Add To Cart</span></a>
                                    {% else %}
                                        <a href="{% url 'home:favourite_ad' id=p.id %}" class="btn btn-fill-out"><i class="icon-basket-loaded"></i><span class="hidden-xs">&nbsp; Add To Cart</span></a>
                                    {% endif %}
                                </td>
                                <td class="product-remove" data-title="Remove"><a href="{% url 'home:favourite_delete' id=p.id %}" class="delete" id="delete"><i class="ti-close"></i></a></td>
                            </tr>
                        {% empty %}
                             <tr>
                                <td >
                                    <h3 style="text-align:center;"> No Wishlist Found</h3>
                                </td>
                             </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END SECTION SHOP -->

<!-- START SECTION SUBSCRIBE NEWSLETTER -->
{% include 'subscribe.html' %}
<!-- START SECTION SUBSCRIBE NEWSLETTER -->

</div>
<!-- END MAIN CONTENT -->


{% endblock %}

templates/owner/checkout.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
{% load thumbnail %}
{% load humanize %}

{% block title %}Bookmarked property{% endblock %}

{% block content %}
     <!-- START SECTION BREADCRUMB -->
<div class="breadcrumb_section bg_gray page-title-mini">
    <div class="container"><!-- STRART CONTAINER -->
        <div class="row align-items-center">
        	<div class="col-md-6">
                <div class="page-title">
            		<h6>Checkout</h6>
                </div>
            </div>
            <div class="col-md-6">
                <ol class="breadcrumb justify-content-md-end">
                    <li class="breadcrumb-item"><a href="{% url "home:home" %}">Home</a></li>
                    <li class="breadcrumb-item active">Checkout</li>
                </ol>
            </div>
        </div>
    </div><!-- END CONTAINER-->
</div>
<!-- END SECTION BREADCRUMB -->

<!-- START MAIN CONTENT -->
<div class="main_content">

<!-- START SECTION SHOP -->
<div class="section">
	<div class="container">
    <form action="." id="signup_form" method="post" data-cities-url="{% url 'order:ajax_load_cities' %}" class="order-form">
                    {% csrf_token %}
        <div class="row">
        	<div class="col-md-6">
            	<div class="heading_s1">
            		<h4>Billing Details</h4>
                </div>

                    <div class="form-group">
                        <input type="text" class="form-control" name="street_address" required="" placeholder="Address ">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="apartment_address" required="" placeholder="Address line2">
                    </div>
                    <div class="form-group">
                        <div class="custom_select">
                            <select id="id_state" class="form-control" name="state">
                                <option value="">State</option>
                                {% for state in states %}
                                  <option value="{{state.id}}">
                                      {{ state }}
                                  </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="custom_select">
                            <select required id="id_city" class="form-control" name="city">
                                <option value="">City</option>
                                {% for cit in cities %}
                                  <option value="{{cit.id}}">
                                      {{ cit }}
                                  </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="chek-form">
                            <div class="custome-checkbox">
                                <input {% if form.save_info.value %}checked{% endif %}  type="checkbox" id="id_save_info" name="save_info">
                                <label for="createaccount"><span>Save this information for the next transaction</span></label>
                            </div>
                        </div>
                    </div>
                    <div class="ship_detail">
                    	<div class="form-group">
                    	<div class="chek-form">
                            <div class="custome-checkbox">
                                <input {% if form.same_billing_address.value %}checked{% endif %} type="checkbox" id="id_same_billing_address" name="same_billing_address">
                                <label for="differentaddress"><span>Shipping address is the same as billing address</span></label>
                            </div>
                        </div>
                    </div>
                    </div>
            </div>
            <div class="col-md-6">
                <div class="order_review">
                    <div class="heading_s1">
                        <h4>Your Orders</h4>
                    </div>
                    <div class="table-responsive order_table">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    {% for order_item in order.items.all %}
                                        <td>{{ order_item.item.title }} <span class="product-qty">x {{ order_item.quantity }}</span></td>
                                        {% if order_item.item.discount_price %}
                                           <td>₦{{ order_item.get_total_discount_item_price|intcomma }}</td>
                                        {% else %}
                                            <td>₦{{ order_item.get_total_item_price |intcomma}}</td>
                                        {% endif %}
                                    {% endfor %}
                                </tr>
                            </tbody>
                            <tfoot>
                                {% for order_item in order.items.all %}
                                    <tr>
                                        <th>SubTotal</th>
                                        <td class="product-subtotal">₦{{ order_item.get_final_price|intcomma }}</td>
                                    </tr>
                                {% endfor %}
                                <tr>
                                    <th>Shipping</th>
                                    <td>₦0</td>
                                </tr>
                                <tr>
                                    <th>Total</th>
                                    <td class="product-subtotal">₦{{ order.get_total|intcomma }}</td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <div class="payment_method">
                        <div class="heading_s1">
                            <h4>Payment</h4>
                        </div>
                        <div class="payment_option">
                            {% for value, name in form.fields.payment_option.choices %}
                                <div class="custome-radio">
                                    <input  type="radio" id="{{ name }}" name="payment_option" value="{{ value }}">
                                    <label for="{{ name }}">{{ name }}</label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-fill-out btn-block">Place order</button>
                </div>
            </div>
        </div>
    </form>
    </div>
</div>
<!-- END SECTION SHOP -->

<!-- START SECTION SUBSCRIBE NEWSLETTER -->
{% include 'subscribe.html' %}
<!-- START SECTION SUBSCRIBE NEWSLETTER -->

</div>
<!-- END MAIN CONTENT -->

{% block script %}
    <script>
        $("#id_state").change(function () {
          var url = $("#signup_form").attr("data-cities-url");  // get the url of the `load_cities` view
          var stateId = $(this).val();  // get the selected country ID from the HTML input

          $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
              'state': stateId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
              $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
            }
          });

        });
      </script>
{% endblock %}
{% endblock %}

templates/owner/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

templates/owner/sub_dropdown_list_options.html
<option value="Select Subcategory" disabled selected>SubCategories</option>
{% for subcategory in subcategories %}
    <option value="{{ subcategory.name }}" {% if subcategory.name == request.GET.subcategory.strip %}selected{% endif %}>{{ subcategory.name }}</option>
{% endfor %}